"""
Auto-generated Airflow DAG for ETL Job #22: User Data ETL V10
Generated by ETL Portal Schedule Manager
"""
from airflow import DAG
from airflow.providers.http.operators.http import SimpleHttpOperator
from airflow.utils.dates import days_ago
from datetime import datetime, timedelta

default_args = {
    'owner': 'etl_portal',
    'depends_on_past': False,
    'start_date': days_ago(1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 3,
    'retry_delay': timedelta(minutes=5),
}

# DAG definition
dag = DAG(
    dag_id='etl_job_22_scheduled',
    default_args=default_args,
    description='Scheduled execution for ETL job: User Data ETL V10',
    schedule_interval='* * * * *',
    catchup=False,
    tags=['etl-portal', 'scheduled', 'job-22'],
    max_active_runs=1,
)

# Task: Trigger ETL job execution via API
execute_job = SimpleHttpOperator(
    task_id='execute_etl_job_22',
    http_conn_id='etl_portal_api',
    endpoint='/api/v1/jobs/execute/22?trigger_source=scheduled',
    method='POST',
    headers={'Content-Type': 'application/json'},
    response_check=lambda response: response.status_code == 201,
    dag=dag,
)
