"""add message rows_failed and airflow_dag_run_id to job_runs

Revision ID: 07bcf9999199
Revises: 8914484203ce
Create Date: 2025-12-23 09:46:59.426053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07bcf9999199'
down_revision: Union[str, None] = '8914484203ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_runs', sa.Column('rows_failed', sa.BigInteger(), nullable=True))
    op.add_column('job_runs', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('job_runs', sa.Column('airflow_dag_run_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_runs', 'airflow_dag_run_id')
    op.drop_column('job_runs', 'message')
    op.drop_column('job_runs', 'rows_failed')
    # ### end Alembic commands ###
