"""add ssl_mode to credentials

Revision ID: 9a33420ca36f
Revises: 2fcc49f70c0a
Create Date: 2025-12-22 17:10:52.922038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a33420ca36f'
down_revision: Union[str, None] = '2fcc49f70c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('ssl_mode', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'ssl_mode')
    # ### end Alembic commands ###
