"""create credentials and etl tables

Revision ID: 2fcc49f70c0a
Revises: 
Create Date: 2025-12-22 17:04:38.582509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fcc49f70c0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('db_type', sa.Enum('POSTGRESQL', 'REDSHIFT', name='databasetype'), nullable=False),
    sa.Column('encrypted_connection_string', sa.String(length=1000), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_id'), 'credentials', ['id'], unique=False)
    op.create_table('etl_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('source_type', sa.Enum('CSV', 'GOOGLE_SHEETS', name='sourcetype'), nullable=False),
    sa.Column('source_config', sa.JSON(), nullable=False),
    sa.Column('destination_type', sa.Enum('POSTGRESQL', 'REDSHIFT', name='destinationtype'), nullable=False),
    sa.Column('destination_config', sa.JSON(), nullable=False),
    sa.Column('load_strategy', sa.String(length=50), nullable=False),
    sa.Column('upsert_keys', sa.JSON(), nullable=True),
    sa.Column('transformation_rules', sa.JSON(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'FAILED', 'PAUSED', name='jobstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_jobs_id'), 'etl_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_etl_jobs_name'), 'etl_jobs', ['name'], unique=False)
    op.create_index(op.f('ix_etl_jobs_status'), 'etl_jobs', ['status'], unique=False)
    op.create_table('column_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_column', sa.String(length=255), nullable=False),
    sa.Column('source_data_type', sa.String(length=100), nullable=True),
    sa.Column('dest_column', sa.String(length=255), nullable=False),
    sa.Column('dest_data_type', sa.String(length=100), nullable=False),
    sa.Column('transformations', sa.JSON(), nullable=True),
    sa.Column('is_calculated', sa.String(length=10), nullable=True),
    sa.Column('calculation_expression', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['etl_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_mappings_id'), 'column_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_column_mappings_job_id'), 'column_mappings', ['job_id'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', name='runstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rows_processed', sa.BigInteger(), nullable=True),
    sa.Column('rows_total', sa.BigInteger(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['etl_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_id'), 'job_runs', ['id'], unique=False)
    op.create_index(op.f('ix_job_runs_job_id'), 'job_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_runs_status'), 'job_runs', ['status'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('airflow_dag_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['etl_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airflow_dag_id')
    )
    op.create_index(op.f('ix_schedules_enabled'), 'schedules', ['enabled'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_job_id'), 'schedules', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_job_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_enabled'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_job_runs_status'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_job_id'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_column_mappings_job_id'), table_name='column_mappings')
    op.drop_index(op.f('ix_column_mappings_id'), table_name='column_mappings')
    op.drop_table('column_mappings')
    op.drop_index(op.f('ix_etl_jobs_status'), table_name='etl_jobs')
    op.drop_index(op.f('ix_etl_jobs_name'), table_name='etl_jobs')
    op.drop_index(op.f('ix_etl_jobs_id'), table_name='etl_jobs')
    op.drop_table('etl_jobs')
    op.drop_index(op.f('ix_credentials_id'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
